# Generated by Django 5.0 on 2023-12-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reminder_time', models.DateTimeField()),
                ('recurring_interval', models.IntegerField(blank=True, null=True)),
                ('urgency', models.IntegerField(blank=True, choices=[(1, '1 - Lowest'), (2, '2'), (3, '3 - Medium'), (4, '4'), (5, '5 - Highest')], null=True)),
            ],
        ),
    ]
