# Generated by Django 5.0.1 on 2024-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
