version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mounts the current directory into /app in the container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # Below is temporary, use Azure managed identity when deploying container to Azure
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - REGISTRATION_CODE=${REGISTRATION_CODE}

  celery:
    build: .
    command: celery -A AutoTasks_backend worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # Below is temporary, use Azure managed identity when deploying container to Azure
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}

  celerybeat:
    build: .
    command: celery -A AutoTasks_backend beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # Below is temporary, use Azure managed identity when deploying container to Azure
      # Celery beat also needs access to env variables because it needs to know about the task's signature,
      # which includes the function names and arguments. Since the API key is an argument, it needs to know the env var API key.
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
